language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rajatsudagade/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run -e CI=true rajatsudagade/docker-react-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-tutorial"
  env: "DockerReactTutorial-env"
  bucket_name: "elasticbeanstalk-us-east-1-359937625789"
  bucket_path: "docker-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
